In [171]:
import pandas as pd
import numpy as np

In [172]:
df=pd.read_csv("3_dataset.csv")
df

id  age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0          0   50       2     168      62    110     80            1     1   
1          1   55       1     156      85    140     90            3     1   
2          2   51       1     165      64    130     70            3     1   
3          3   48       2     169      82    150    100            1     1   
4          4   47       1     156      56    100     60            1     1   
...      ...  ...     ...     ...     ...    ...    ...          ...   ...   
68583  99993   52       2     168      76    120     80            1     1   
68584  99995   61       1     158     126    140     90            2     2   
68585  99996   52       2     183     105    180     90            3     1   
68586  99998   61       1     163      72    135     80            1     2   
68587  99999   56       1     170      72    120     80            2     1   

       smoke  alco  active  cardio  diagnosis  
0          0     0       1       0          2  
1          0     0       1       1          3  
2          0     0       0       1          2  
3          0     0       1       1          3  
4          0     0       0       0          1  
...      ...   ...     ...     ...        ...  
68583      1     0       1       0          2  
68584      0     0       1       1          3  
68585      0     1       0       1          3  
68586      0     0       0       1          2  
68587      0     0       1       0          2  

[68588 rows x 14 columns]

In [173]:
X =  df.drop(columns="diagnosis",axis=1)
Y =  df["diagnosis"]

In [174]:
print(X)

          id  age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0          0   50       2     168      62    110     80            1     1   
1          1   55       1     156      85    140     90            3     1   
2          2   51       1     165      64    130     70            3     1   
3          3   48       2     169      82    150    100            1     1   
4          4   47       1     156      56    100     60            1     1   
...      ...  ...     ...     ...     ...    ...    ...          ...   ...   
68583  99993   52       2     168      76    120     80            1     1   
68584  99995   61       1     158     126    140     90            2     2   
68585  99996   52       2     183     105    180     90            3     1   
68586  99998   61       1     163      72    135     80            1     2   
68587  99999   56       1     170      72    120     80            2     1   

       smoke  alco  active  cardio  
0          0     0       1

In [175]:
print(Y)

0        2
1        3
2        2
3        3
4        1
        ..
68583    2
68584    3
68585    3
68586    2
68587    2
Name: diagnosis, Length: 68588, dtype: int64


In [176]:
from sklearn.model_selection import train_test_split

Xtrain,Xtest,Ytrain,Ytest = train_test_split(X,Y,test_size=0.2, stratify=Y, random_state=2 )



In [177]:
print(Xtest)

          id  age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
52358  76221   42       2     175      85    120     80            1     1   
35116  51191   39       2     176      90    120     80            1     1   
66430  96818   57       1     150      73    130     80            1     1   
32424  47288   55       1     152      65    110     70            1     1   
65036  94761   47       2     168      60    160     70            1     1   
...      ...  ...     ...     ...     ...    ...    ...          ...   ...   
6438    9390   42       1     164      65    120     80            1     1   
40673  59296   58       2     159      59    120     80            3     3   
41807  60955   43       2     177      77    120     80            1     1   
42819  62435   57       2     178      69    135     85            2     2   
49578  72213   56       1     163      97    120     80            3     3   

       smoke  alco  active  cardio  
52358      1     0       0

In [178]:
from sklearn.linear_model import LogisticRegression

In [179]:
lr = LogisticRegression()
lr.fit(Xtrain,Ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [180]:
test.copy()
test["predicted"]=lr.predict(Xtest)
test=test.astype(float)
test

id   age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
52358  76221.0  42.0     2.0   175.0    85.0  120.0   80.0          1.0   1.0   
35116  51191.0  39.0     2.0   176.0    90.0  120.0   80.0          1.0   1.0   
66430  96818.0  57.0     1.0   150.0    73.0  130.0   80.0          1.0   1.0   
32424  47288.0  55.0     1.0   152.0    65.0  110.0   70.0          1.0   1.0   
65036  94761.0  47.0     2.0   168.0    60.0  160.0   70.0          1.0   1.0   
...        ...   ...     ...     ...     ...    ...    ...          ...   ...   
6438    9390.0  42.0     1.0   164.0    65.0  120.0   80.0          1.0   1.0   
40673  59296.0  58.0     2.0   159.0    59.0  120.0   80.0          3.0   3.0   
41807  60955.0  43.0     2.0   177.0    77.0  120.0   80.0          1.0   1.0   
42819  62435.0  57.0     2.0   178.0    69.0  135.0   85.0          2.0   2.0   
49578  72213.0  56.0     1.0   163.0    97.0  120.0   80.0          3.0   3.0   

       smoke  alco  active  cardio  diagnosis  predicted  
52358    1.0   0.0     0.0     0.0        2.0        2.0  
35116    1.0   0.0     0.0     0.0        2.0        2.0  
66430    0.0   0.0     1.0     1.0        2.0        2.0  
32424    0.0   0.0     1.0     0.0        1.0        2.0  
65036    0.0   0.0     0.0     1.0        2.0        3.0  
...      ...   ...     ...     ...        ...        ...  
6438     0.0   0.0     0.0     0.0        2.0        2.0  
40673    0.0   0.0     1.0     0.0        2.0        2.0  
41807    0.0   0.0     1.0     1.0        2.0        2.0  
42819    0.0   0.0     1.0     0.0        3.0        2.0  
49578    0.0   0.0     0.0     1.0        2.0        2.0  

[13718 rows x 15 columns]

In [181]:
test.shape

(13718, 15)

In [182]:
lr.coef_, lr.intercept_

(array([[ 1.04477555e-05,  1.31790522e-02,  9.57424108e-05,
          1.09050305e-01, -1.96881224e-03, -1.04232978e-01,
         -7.10263999e-02, -2.07686208e-04,  3.24917348e-04,
         -1.04836820e-05, -3.78310988e-05,  7.33836497e-04,
         -2.16111759e-03],
        [ 2.52239266e-06,  2.33065109e-02,  6.66714990e-04,
          6.60589459e-02,  1.21345469e-03, -7.27776602e-02,
         -1.52304196e-02, -1.24214119e-03, -6.82618002e-05,
         -9.80108095e-05, -9.54055693e-05,  9.02766750e-05,
         -2.15989357e-03],
        [-1.29701482e-05, -3.64855630e-02, -7.62457401e-04,
         -1.75109251e-01,  7.55357551e-04,  1.77010638e-01,
          8.62568195e-02,  1.44982740e-03, -2.56655548e-04,
          1.08494492e-04,  1.33236668e-04, -8.24113172e-04,
          4.32101116e-03]]), array([ 0.0007616 ,  0.00035782, -0.00111942]))

In [197]:
coef = np.vstack((lr.coef_.T,lr.intercept_))
coef

array([[ 1.04477555e-05,  2.52239266e-06, -1.29701482e-05],
       [ 1.31790522e-02,  2.33065109e-02, -3.64855630e-02],
       [ 9.57424108e-05,  6.66714990e-04, -7.62457401e-04],
       [ 1.09050305e-01,  6.60589459e-02, -1.75109251e-01],
       [-1.96881224e-03,  1.21345469e-03,  7.55357551e-04],
       [-1.04232978e-01, -7.27776602e-02,  1.77010638e-01],
       [-7.10263999e-02, -1.52304196e-02,  8.62568195e-02],
       [-2.07686208e-04, -1.24214119e-03,  1.44982740e-03],
       [ 3.24917348e-04, -6.82618002e-05, -2.56655548e-04],
       [-1.04836820e-05, -9.80108095e-05,  1.08494492e-04],
       [-3.78310988e-05, -9.54055693e-05,  1.33236668e-04],
       [ 7.33836497e-04,  9.02766750e-05, -8.24113172e-04],
       [-2.16111759e-03, -2.15989357e-03,  4.32101116e-03],
       [ 7.61603503e-04,  3.57819308e-04, -1.11942281e-03]])

In [198]:
coef[:,0]

array([ 1.04477555e-05,  1.31790522e-02,  9.57424108e-05,  1.09050305e-01,
       -1.96881224e-03, -1.04232978e-01, -7.10263999e-02, -2.07686208e-04,
        3.24917348e-04, -1.04836820e-05, -3.78310988e-05,  7.33836497e-04,
       -2.16111759e-03,  7.61603503e-04])

In [199]:
scores= test.iloc[:,:14] @ coef
scores
lr.classes_

array([1, 2, 3])

In [200]:
scores.set_axis( ["A","B","C"], axis=1)

A         B         C
52358  2.078065  2.883480 -4.961545
35116  1.876227  2.822551 -4.698778
66430 -1.255531  0.888581  0.366950
32424  1.230808  2.449104 -3.679912
65036 -1.837676 -0.206836  2.044511
...         ...       ...       ...
6438   0.219569  1.963420 -2.182988
40673  0.419465  2.122767 -2.542232
41807  2.164183  2.988718 -5.152901
42819  0.573366  2.208484 -2.781850
49578  0.886456  2.416166 -3.302622

[13718 rows x 3 columns]

In [187]:
# def sigmoid(x):
#   return 1/ (1+np.exp(-x))



In [195]:
# scores = sigmoid(test.iloc[:,:14] @ coef)
# # scores.astype(str)
# scores = scores.set_axis([c+"-score" for c in lr.classes_], axis=1)
# scores.head()

UFuncTypeError: ignored

In [189]:
pd.concat((test,scores), axis=1)

id   age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
52358  76221.0  42.0     2.0   175.0    85.0  120.0   80.0          1.0   1.0   
35116  51191.0  39.0     2.0   176.0    90.0  120.0   80.0          1.0   1.0   
66430  96818.0  57.0     1.0   150.0    73.0  130.0   80.0          1.0   1.0   
32424  47288.0  55.0     1.0   152.0    65.0  110.0   70.0          1.0   1.0   
65036  94761.0  47.0     2.0   168.0    60.0  160.0   70.0          1.0   1.0   
...        ...   ...     ...     ...     ...    ...    ...          ...   ...   
6438    9390.0  42.0     1.0   164.0    65.0  120.0   80.0          1.0   1.0   
40673  59296.0  58.0     2.0   159.0    59.0  120.0   80.0          3.0   3.0   
41807  60955.0  43.0     2.0   177.0    77.0  120.0   80.0          1.0   1.0   
42819  62435.0  57.0     2.0   178.0    69.0  135.0   85.0          2.0   2.0   
49578  72213.0  56.0     1.0   163.0    97.0  120.0   80.0          3.0   3.0   

       smoke  alco  active  cardio  diagnosis  predicted         0         1  \
52358    1.0   0.0     0.0     0.0        2.0        2.0  2.078065  2.883480   
35116    1.0   0.0     0.0     0.0        2.0        2.0  1.876227  2.822551   
66430    0.0   0.0     1.0     1.0        2.0        2.0 -1.255531  0.888581   
32424    0.0   0.0     1.0     0.0        1.0        2.0  1.230808  2.449104   
65036    0.0   0.0     0.0     1.0        2.0        3.0 -1.837676 -0.206836   
...      ...   ...     ...     ...        ...        ...       ...       ...   
6438     0.0   0.0     0.0     0.0        2.0        2.0  0.219569  1.963420   
40673    0.0   0.0     1.0     0.0        2.0        2.0  0.419465  2.122767   
41807    0.0   0.0     1.0     1.0        2.0        2.0  2.164183  2.988718   
42819    0.0   0.0     1.0     0.0        3.0        2.0  0.573366  2.208484   
49578    0.0   0.0     0.0     1.0        2.0        2.0  0.886456  2.416166   

              2  
52358 -4.961545  
35116 -4.698778  
66430  0.366950  
32424 -3.679912  
65036  2.044511  
...         ...  
6438  -2.182988  
40673 -2.542232  
41807 -5.152901  
42819 -2.781850  
49578 -3.302622  

[13718 rows x 18 columns]